baseURL = 'https://arenarintel.com/'
locale = "en-US"
title = 'Arenar Intel'
cleanDestinationDir = true

buildFuture = true

disableKinds = ["taxonomy", "term"]
[taxonomies]

[params]
  description = 'The Global Intelligence Feed - delivering fast, verified reporting on the events, conflicts and decisions shaping the modern world.'
  logo = '/images/logo-512.png'
  twitter = '@arenarintel'

  xbar = "Iran has agreed to a ceasefire deal after intense negotiations in Geneva."
  xbarlink = "https://x.com/ArenarIntel/status/1234567890"

[module]
  [module.hugoVersion]
    extended = false
    min = '0.146.0'