baseURL = 'https://www.arenarintel.com/'
locale = "en-US"
title = 'Arenar Intel'

[params]
  description = 'The world moves fast. Stay informed faster. Real-time global intelligence and media updates.'

[module]
  [module.hugoVersion]
    extended = false
    min = '0.146.0'

disableKinds = ["taxonomy", "term"]

cleanDestinationDir = true