backend:
  name: git-gateway
  branch: main

media_folder: "static/uploads"
public_folder: "/uploads"

collections:
  - name: "articles"
    label: "Articles"

    folder: "content/intel"

    create: true

    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"

    format: "toml"

    extension: "md"

    fields:
      - label: "Title"
        name: "title"
        widget: "string"

      - label: "Publish Date"
        name: "date"
        widget: "datetime"

      - label: "Draft"
        name: "draft"
        widget: "boolean"
        default: false

      - label: "Card Type"
        name: "card"
        widget: "select"
        options:
          - "featured"
          - "compact"
          - "basic"
          - "text"
          - "grid"

      - label: "Homepage Featured"
        name: "homepage_featured"
        widget: "boolean"
        required: false
        default: false

      - label: "Featured Image"
        name: "image"
        widget: "image"
        required: false

      - label: "Summary"
        name: "summary"
        widget: "text"
        required: false

      - label: "Body"
        name: "body"
        widget: "markdown"