backend:
  name: git-gateway
  branch: main

media_folder: "static/uploads"
public_folder: "/uploads"

collections:
  - name: "posts"
    label: "Posts"
    folder: "content/posts"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"

    fields:
      - { label: "Title", name: "title", widget: "string" }

      - { label: "Date", name: "date", widget: "datetime" }

      - { label: "Description", name: "description", widget: "text" }

      - { label: "Card Type", name: "card", widget: "select", options: ["featured", "text", "compact", "basic", "grid"] }

      - { label: "Homepage Featured", name: "homepage_featured", widget: "boolean", required: false }

      - { label: "Body", name: "body", widget: "markdown" }